# Generated by Django 3.0.2 on 2020-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('player_lname', models.CharField(max_length=200)),
                ('player_fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('team', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('g', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('int_yds', models.IntegerField()),
                ('int_td', models.IntegerField()),
                ('pass_def', models.IntegerField()),
                ('ffb', models.IntegerField()),
                ('fr', models.IntegerField()),
                ('fb_yds', models.IntegerField()),
                ('fb_td', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('solo', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('tfl', models.IntegerField()),
                ('qb_hits', models.IntegerField()),
                ('sfty', models.IntegerField()),
                ('player_id', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='defense.Players')),
            ],
        ),
    ]
